version: '3.8'

services:
  backend:
    build:
      context: ./apps/local-api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      # Persist SQLite database and downloaded SFace/YuNet face models
      - ./apps/local-api/smart_lockers.db:/app/smart_lockers.db
      - ./apps/local-api/models_cache:/app/models_cache
      - ./apps/local-api/.env:/app/.env
      # Mount dev tree to access USB Serial controllers and Webcams dynamically
      - /dev:/dev
    restart: always

  frontend:
    build:
      context: ./apps/kiosk-ui
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    restart: always
